=== JG0328/DietCalculator/DietCalculator/Resources/recetas.dtd
<!ELEMENT recetas (receta+)>
<!ELEMENT receta (nombre, ingredientes, herramientas, procedimiento)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (nombre, calorias, grasas)>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT grasas (#PCDATA)>
<!ELEMENT herramientas (herramienta+)>
<!ELEMENT herramienta (#PCDATA)>
<!ELEMENT procedimiento (paso+)>
<!ELEMENT paso (#PCDATA)>

=== JG0328/DietCalculator/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetas SYSTEM "recetas.dtd">
<recetas>
    <receta>
        <nombre>Receta 1</nombre>
        <ingredientes>
            <ingrediente>
                <nombre>Ingrediente 1</nombre>
                <calorias>100</calorias>
                <grasas>100</grasas>
            </ingrediente>
        </ingredientes>
        <herramientas></herramientas>
        <procedimiento></procedimiento>
    </receta>
    <receta>
        <nombre>Receta 2</nombre>
        <ingredientes>
            <ingrediente>
                <nombre>Ingrediente 2</nombre>
                <calorias>80</calorias>
                <grasas>80</grasas>
            </ingrediente>
        </ingredientes>
        <herramientas></herramientas>
        <procedimiento></procedimiento>
    </receta>
</recetas>

=== JG0328/DietCalculator/DietCalculator/Resources/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetas SYSTEM "recetas.dtd">
<recetas>
  <receta>
    <nombre>Receta 1</nombre>
    <ingredientes>
      <ingrediente>
        <nombre>Ingrediente 1</nombre>
        <calorias>100</calorias>
        <grasas>100</grasas>
      </ingrediente>
    </ingredientes>
    <herramientas>
      <herramienta>Herramienta 1</herramienta>
    </herramientas>
    <procedimiento>
      <paso>1</paso>
      <paso>2</paso>
    </procedimiento>
  </receta>
  <receta>
    <nombre>Receta 2</nombre>
    <ingredientes>
      <ingrediente>
        <nombre>Ingrediente 2</nombre>
        <calorias>80</calorias>
        <grasas>80</grasas>
      </ingrediente>
    </ingredientes>
    <herramientas>
      <herramienta>Herramienta 2</herramienta>
    </herramientas>
    <procedimiento>
      <paso>1</paso>
      <paso>2</paso>
    </procedimiento>
  </receta>
</recetas>
